### PR TITLE
add stats option to renderer

### PR DESCRIPTION
**Pull request by SaFrMo**
I ended up needing this for performance testing and thought it'd be useful for others:

```html
<template>
  <!-- Add a stats.js FPS monitor, no further config required -->
  <Renderer stats>...</Renderer>

  <!-- Optionally pass a function to handle the created Stats object yourself -->
  <Renderer :stats="onStatsCreated">...</Renderer>
</template>

<script>
// only needed if passing a function to `stats`
export default {
  methods: {
    onStatsCreated(stats) {
      // do something with the Stats object
    }
  }
}
</script>
```

Screen shot of three white cubes in a black background with a frames-per-second graph in the top left.

That also made me think that maybe there should be another `onBeforeRender`-like callback called `onAfterRender` - happy to add that in if you'd like @klevron !

### CODE REVIEW

**Comment by klevron** [comment]
Good idea 👍  but I was thinking about not adding to much options to renderer. Can you try to make a Stats component in components/misc ? And use devDependencies instead. I will handle *onAfterRender*.

**Comment by SaFrMo** [comment]
Good thought, will do! It looks like the `components` folder is focused on non-core components, is that correct? Love that idea if so, it'll be great to have these features easily available without weighing down the core library.

**Comment by klevron** [comment]
Yes `components` is a little bit like examples in threejs :)

**Comment by SaFrMo** [comment]
Closing in favor of #41

**Pull request closed without merging**
