### PR TITLE
gltf no animations

### PR DESCRIPTION
**Pull request by roy2an**

### CODE REVIEW

**Comment by max-arias** [comment]
+1 I can confirm animations are lost in `GltfModel`

**Comment by SaFrMo** [comment]
This looks good to me @klevron - any thoughts? Thanks @roy2an !

**Comment by klevron** [comment]
Thanks 👍

**Comment by ikantthink** [comment]
It looks likes this is because the onLoad from the gltf loader component is returning only the scene and the animations are not in the scene object. They are in `gltf.animations`.
```
var GLTF = defineComponent({
  extends: Model,
  created() {
    const loader = new GLTFLoader();
    loader.load(this.src, (gltf) => {
      this.onLoad(gltf.scene);
    }, this.onProgress, this.onError);
  }
});
```

**Pull request merged**
